import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import { fileURLToPath } from "node:url";

const prod = process.argv[2] === "production";
const projectDirectory = fileURLToPath(new URL(".", import.meta.url));

const context = await esbuild.context({
  absWorkingDir: projectDirectory,
  banner: {
    js: "/* Generated by esbuild. Source: https://github.com/Kirbosh/DataliZation */",
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "node16",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}

