/* Generated by esbuild. Source: https://github.com/Kirbosh/DataliZation */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DatalizationPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/views/datalizationView.ts
var import_obsidian = require("obsidian");
var DATALIZATION_VIEW_TYPE = "datalization-monthly-dashboard";
var DAILY_NOTE_PATTERN = /^(\d{4})-(\d{2})-(\d{2})$/;
var FRONTMATTER_PATTERN = /^---\s*\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/;
var DatalizationView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
    this.renderGeneration = 0;
    const now = /* @__PURE__ */ new Date();
    this.currentMonth = new Date(now.getFullYear(), now.getMonth(), 1);
  }
  getViewType() {
    return DATALIZATION_VIEW_TYPE;
  }
  getDisplayText() {
    return "Datalization";
  }
  getIcon() {
    return "calendar-days";
  }
  async onOpen() {
    this.registerEvent(this.app.metadataCache.on("changed", (file) => {
      if (DAILY_NOTE_PATTERN.test(file.basename)) this.scheduleRender();
    }));
    this.registerEvent(this.app.vault.on("create", (file) => this.handleVaultChange(file)));
    this.registerEvent(this.app.vault.on("delete", (file) => this.handleVaultChange(file)));
    this.registerEvent(this.app.vault.on("rename", (file) => this.handleVaultChange(file)));
    await this.render();
  }
  async onClose() {
    if (this.refreshTimer !== void 0) window.clearTimeout(this.refreshTimer);
    this.renderGeneration += 1;
  }
  getState() {
    return { month: this.toMonthKey(this.currentMonth) };
  }
  async setState(state, result) {
    await super.setState(state, result);
    if (typeof state.month === "string" && /^\d{4}-\d{2}$/.test(state.month)) {
      const [year, month] = state.month.split("-").map(Number);
      this.currentMonth = new Date(year, month - 1, 1);
    }
    if (this.contentEl.isConnected) await this.render();
  }
  handleVaultChange(file) {
    if (file instanceof import_obsidian.TFile && file.extension === "md" && DAILY_NOTE_PATTERN.test(file.basename)) {
      this.scheduleRender();
    }
  }
  scheduleRender() {
    if (this.refreshTimer !== void 0) window.clearTimeout(this.refreshTimer);
    this.refreshTimer = window.setTimeout(() => {
      this.refreshTimer = void 0;
      void this.render();
    }, 150);
  }
  async render() {
    const generation = ++this.renderGeneration;
    const records = await this.readMonth(this.currentMonth);
    if (generation !== this.renderGeneration) return;
    this.contentEl.empty();
    this.contentEl.addClass("datalization-view");
    const shell = this.contentEl.createDiv({ cls: "datalization-shell" });
    this.renderHeader(shell);
    this.renderSummary(shell, records);
    this.renderCalendar(shell, records);
    this.renderLegend(shell);
  }
  renderHeader(container) {
    const header = container.createDiv({ cls: "datalization-header" });
    const heading = header.createDiv({ cls: "datalization-heading" });
    heading.createEl("h1", {
      text: this.currentMonth.toLocaleDateString(void 0, { month: "long", year: "numeric" })
    });
    const navigation = header.createDiv({ cls: "datalization-navigation" });
    const previousButton = navigation.createEl("button", {
      cls: "datalization-icon-button",
      attr: { "aria-label": "Previous month", title: "Previous month" }
    });
    (0, import_obsidian.setIcon)(previousButton, "chevron-left");
    previousButton.addEventListener("click", () => this.changeMonth(-1));
    const todayButton = navigation.createEl("button", {
      cls: "datalization-today-button",
      text: "Today"
    });
    todayButton.addEventListener("click", () => {
      const today = /* @__PURE__ */ new Date();
      this.currentMonth = new Date(today.getFullYear(), today.getMonth(), 1);
      void this.render();
    });
    const nextButton = navigation.createEl("button", {
      cls: "datalization-icon-button",
      attr: { "aria-label": "Next month", title: "Next month" }
    });
    (0, import_obsidian.setIcon)(nextButton, "chevron-right");
    nextButton.addEventListener("click", () => this.changeMonth(1));
  }
  renderSummary(container, records) {
    const summary = container.createDiv({ cls: "datalization-summary" });
    this.createSummaryCard(summary, "Days logged", String(records.length));
    this.createSummaryCard(summary, "Average mood", this.average(records.map((record) => record.mood)));
    this.createSummaryCard(summary, "Average sleep", this.average(records.map((record) => record.sleep), " h"));
  }
  createSummaryCard(container, label, value) {
    const card = container.createDiv({ cls: "datalization-summary-card" });
    card.createDiv({ cls: "datalization-summary-value", text: value });
    card.createDiv({ cls: "datalization-summary-label", text: label });
  }
  renderCalendar(container, records) {
    const calendar = container.createDiv({ cls: "datalization-calendar" });
    const weekdayHeader = calendar.createDiv({ cls: "datalization-weekdays" });
    for (const weekday of ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]) {
      weekdayHeader.createDiv({ cls: "datalization-weekday", text: weekday });
    }
    const grid = calendar.createDiv({ cls: "datalization-grid" });
    const firstWeekday = new Date(
      this.currentMonth.getFullYear(),
      this.currentMonth.getMonth(),
      1
    ).getDay();
    for (let index = 0; index < firstWeekday; index += 1) {
      grid.createDiv({ cls: "datalization-day-spacer" });
    }
    const recordsByDay = new Map(records.map((record) => [record.date.getDate(), record]));
    const daysInMonth = new Date(
      this.currentMonth.getFullYear(),
      this.currentMonth.getMonth() + 1,
      0
    ).getDate();
    for (let day = 1; day <= daysInMonth; day += 1) {
      this.renderDay(grid, day, recordsByDay.get(day));
    }
  }
  renderDay(grid, day, record) {
    const date = new Date(this.currentMonth.getFullYear(), this.currentMonth.getMonth(), day);
    const card = grid.createEl("button", {
      cls: `datalization-day${record ? " datalization-day-has-data" : " datalization-day-empty"}`,
      attr: {
        "aria-label": this.describeDay(date, record),
        title: this.describeDay(date, record)
      }
    });
    const face = card.createDiv({ cls: "datalization-day-face" });
    face.createDiv({ cls: "datalization-date-number", text: String(day) });
    if (!record) {
      face.createDiv({ cls: "datalization-no-data", text: "\u2014" });
      return;
    }
    if (record.mood !== null) {
      const gradient = this.moodGradient(record.mood);
      card.style.setProperty("--datalization-mood-hue", String(gradient.startHue));
      card.style.setProperty("--datalization-mood-end-hue", String(gradient.endHue));
      face.createDiv({ cls: "datalization-mood", text: this.formatNumber(record.mood) });
    } else {
      card.addClass("datalization-day-no-mood");
      face.createDiv({ cls: "datalization-mood datalization-value-missing", text: "\u2014" });
    }
    const sleepPanel = face.createDiv({ cls: "datalization-sleep" });
    sleepPanel.createSpan({ text: record.sleep === null ? "\u2014" : this.formatNumber(record.sleep) });
    const indicators = card.createDiv({ cls: "datalization-indicators" });
    if (record.mediaMade) {
      indicators.createSpan({
        cls: "datalization-indicator datalization-indicator-media-made",
        attr: { "aria-label": "Media made" }
      });
    }
    if (record.highFluctuation) {
      indicators.createSpan({
        cls: "datalization-indicator datalization-indicator-fluctuation",
        attr: { "aria-label": "High fluctuation" }
      });
    }
    if (record.mediaConsumed) {
      indicators.createSpan({
        cls: "datalization-indicator datalization-indicator-media-consumed",
        attr: { "aria-label": "Media consumed" }
      });
    }
    card.addEventListener("click", () => {
      void this.app.workspace.getLeaf(false).openFile(record.file);
    });
  }
  renderLegend(container) {
    const legend = container.createDiv({ cls: "datalization-legend" });
    const gradient = legend.createDiv({ cls: "datalization-gradient-legend" });
    gradient.createSpan({ text: "Low mood" });
    gradient.createSpan({ cls: "datalization-gradient" });
    gradient.createSpan({ text: "High mood" });
    const flags = legend.createDiv({ cls: "datalization-flag-legend" });
    const made = flags.createSpan({ cls: "datalization-legend-item" });
    made.createSpan({ cls: "datalization-indicator datalization-indicator-media-made" });
    made.createSpan({ text: "Media made" });
    const fluctuation = flags.createSpan({ cls: "datalization-legend-item" });
    fluctuation.createSpan({ cls: "datalization-indicator datalization-indicator-fluctuation" });
    fluctuation.createSpan({ text: "High fluctuation" });
    const consumed = flags.createSpan({ cls: "datalization-legend-item" });
    consumed.createSpan({ cls: "datalization-indicator datalization-indicator-media-consumed" });
    consumed.createSpan({ text: "Media consumed" });
  }
  changeMonth(offset) {
    this.currentMonth = new Date(
      this.currentMonth.getFullYear(),
      this.currentMonth.getMonth() + offset,
      1
    );
    void this.render();
  }
  async readMonth(month) {
    const prefix = `${month.getFullYear()}-${String(month.getMonth() + 1).padStart(2, "0")}-`;
    const matchingFiles = this.app.vault.getMarkdownFiles().filter((file) => {
      return file.basename.startsWith(prefix) && DAILY_NOTE_PATTERN.test(file.basename);
    });
    const records = await Promise.all(matchingFiles.map(async (file) => {
      var _a, _b;
      const match = DAILY_NOTE_PATTERN.exec(file.basename);
      if (!match) return null;
      const year = Number(match[1]);
      const monthIndex = Number(match[2]) - 1;
      const day = Number(match[3]);
      const date = new Date(year, monthIndex, day);
      if (date.getFullYear() !== year || date.getMonth() !== monthIndex || date.getDate() !== day) return null;
      let frontmatter = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
      if (!frontmatter) {
        const content = await this.app.vault.cachedRead(file);
        const yaml = (_b = FRONTMATTER_PATTERN.exec(content)) == null ? void 0 : _b[1];
        if (yaml) {
          try {
            frontmatter = (0, import_obsidian.parseYaml)(yaml);
          } catch (error) {
            console.warn(`Datalization: could not parse frontmatter in ${file.path}`, error);
          }
        }
      }
      const data = frontmatter ?? {};
      return {
        date,
        file,
        mood: this.toNumber(data["Mood"] ?? data["mood"]),
        sleep: this.toNumber(data["Hours slept"] ?? data["hours slept"]),
        mediaMade: this.toBoolean(data["Media made"]),
        mediaConsumed: this.toBoolean(data["Media consumed"]),
        highFluctuation: this.toBoolean(data["High fluctuation"])
      };
    }));
    return records.filter((record) => record !== null).sort((left, right) => left.date.getTime() - right.date.getTime());
  }
  describeDay(date, record) {
    const lines = [date.toLocaleDateString(void 0, { dateStyle: "long" })];
    if (!record) return `${lines[0]}: no daily note`;
    lines.push(`Mood: ${record.mood ?? "not set"}`);
    lines.push(`Hours slept: ${record.sleep ?? "not set"}`);
    if (record.mediaMade) lines.push("Media made");
    if (record.highFluctuation) lines.push("High fluctuation");
    if (record.mediaConsumed) lines.push("Media consumed");
    return lines.join("\n");
  }
  moodGradient(mood) {
    const clamped = Math.min(10, Math.max(1, mood));
    const normalized = (clamped - 1) / 9;
    const startHue = Math.round(normalized * 86);
    return {
      startHue,
      endHue: Math.round(startHue + normalized * 69)
    };
  }
  average(values, suffix = "") {
    const numericValues = values.filter((value) => value !== null);
    if (!numericValues.length) return "\u2014";
    const average = numericValues.reduce((sum, value) => sum + value, 0) / numericValues.length;
    return `${this.formatNumber(Math.round(average * 10) / 10)}${suffix}`;
  }
  toNumber(value) {
    if (typeof value === "number" && Number.isFinite(value)) return value;
    if (typeof value === "string" && value.trim() !== "") {
      const parsed = Number(value);
      if (Number.isFinite(parsed)) return parsed;
    }
    return null;
  }
  toBoolean(value) {
    return value === true || value === 1 || typeof value === "string" && value.toLowerCase() === "true";
  }
  formatNumber(value) {
    return new Intl.NumberFormat(void 0, { maximumFractionDigits: 2 }).format(value);
  }
  toMonthKey(date) {
    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
  }
};

// src/main.ts
var DatalizationPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    this.registerView(
      DATALIZATION_VIEW_TYPE,
      (leaf) => new DatalizationView(leaf)
    );
    this.addRibbonIcon("calendar-days", "Open Datalization", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-monthly-dashboard",
      name: "Open monthly dashboard",
      callback: () => {
        void this.activateView();
      }
    });
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(DATALIZATION_VIEW_TYPE);
  }
  async activateView() {
    const existingLeaf = this.app.workspace.getLeavesOfType(DATALIZATION_VIEW_TYPE)[0];
    const leaf = existingLeaf ?? this.app.workspace.getLeaf("tab");
    if (!existingLeaf) {
      await leaf.setViewState({ type: DATALIZATION_VIEW_TYPE, active: true });
    }
    this.app.workspace.revealLeaf(leaf);
  }
};

